test commit to new rep
bigbagabum/places pull request #1
Opened 2022-11-08 10:04 UTC by bigbagabum

2022-12-12 21:39 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/207160199-2fcf2f1e-1dff-4226-aae1-29b601a41582.png)

2023-01-07 10:42 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/211146266-e0768dc6-4523-469f-ac25-c2e059eea18b.png)

2023-01-07 10:43 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/211146283-034f2d16-b804-49a4-b4d1-2416e1f3d4f4.png)

2023-01-07 10:43 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/211146300-b298d0e5-3dce-40bd-be52-993a030cf449.png)

2023-01-09 16:46 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/211361782-94c9df92-b844-4957-9992-d294035f3e15.png)

2023-01-19 16:21 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/213496288-2e610330-a22f-4b28-a49d-699a554fb2d0.png)

2023-01-23 20:36 UTC, internetova reviewed
### Давайте начнем с этого:


**Навести порядок в файлах**. Обратите внимание как вы называете файлы - анализатор кода подсказывает, а вы игнорируете.
Вот такое делать не надо:
/// ignore: file_names

<img width="261" alt="Снимок экрана 2023-01-23 в 22 29 53" src="https://user-images.githubusercontent.com/39735343/214144956-68b5e535-6c3b-425b-8c31-19fe5919b8ca.png">

Избавиться от хинтов в анализаторе кода. Анализатор должен быть чистым.

Ознакомьтесь пожалуйста:
https://dart.dev/guides/language/effective-dart/style

Экспорт иконок делаем в svg
Экспорт иконок из фигмы
Видео:
https://t.me/c/1400009736/7684

**Экран фильтр**
1. Хорошо бы поправить верстку:
Кнопка назад в аппбаре
Категории не выровнены по центру
Кнопка показать совсем прижата к низу

<img width="295" alt="Снимок экрана 2023-01-23 в 22 37 01" src="https://user-images.githubusercontent.com/39735343/214144993-8023594a-0e19-490e-8ef3-813082bf19b5.png">

Надо определить шрифты и необходимые цвета в теме. Также добавить другие настройки в тему. Смотрите комментарии в коде.

**Экран поиск**

Поле поиска сверстано не корректно:
Текст не по центру
Иконке фильтра быть не должно, вместо неё при вводе текста должна появляться кнопка очистить

Результаты поиска - надо подсвечивать найденные символы жирным

Если ничего не найдено надо отображать соответствующую информацию - смотрите в дизайне

Также надо сохранять результаты поиска. Сейчас это можно делать в отдельном классе, например.

**Экран добавления нового места**

На широту/долготу хорошо бы добавить формате чтобы не давать вводить запрещенные символы. На все поля надо сделать проверку на корректность введенных данных.

В полях при вводе надо бы разметить иконку очистить - смотре в дизайне

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +// ignore_for_file: non_constant_identifier_names
Не игнорируем предупреждения анализатора, а следуем его подсказкам

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +import '../../domain/sight.dart';
Делайте все через package

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +class AddSightScreen extends StatefulWidget {
Обратите внимание, что у вас названия файлов такие же как названия классов. Рекомендую заглянуть в анализатор кода - он должен подсказать

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +  void _IsAllFieldsFilled() {
название методов с маленькой буквы пишем

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +  void _IsAllFieldsFilled() {
https://dart.dev/guides/language/effective-dart/style

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +                          Sight newPlace = Sight(
лучше `final newPlace`

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/AddSightScreen.dart
> +                  )),
не забывайте ставить запятые чтобы не было скопления скобок

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/CategoriesScreen.dart
> +import 'AddSightScreen.dart';
https://dart.dev/guides/language/effective-dart/style

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/CategoriesScreen.dart
> +    if (e == true) {
`if (e)` заменяет вашу запись

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/CategoriesScreen.dart
> +          image: AssetImage('lib/ui/res/icons/FilterItem.png'),
Экспорт иконок из фигмы
Видео:
https://t.me/c/1400009736/7684

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/CategoriesScreen.dart
> +      return Text('');
а вам надо пустой текст показывать? может тогда ничего не показывать?

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +import '../../domain/sight.dart';
все импорты делаем через package

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +  late List<Sight> filteredSightsList = [];
зачем вы пишите late если уже присвоили пустой список?

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +  var TextSearchFieldController = TextEditingController();
а почему var? final

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +  Widget SeightLine(Sight inputSight) {
Методы или классы
Flutter Voronezh Meetup | Build methods vs Widget:
https://youtu.be/PNJDqt3Z_7Q

Сравнение виджетов и вспомогательных методов:
https://youtu.be/IOyq-eTRhvo

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +            style: TextStyle(
а почему у нас тут настройки шрифта? вы же писали тему? там шрифты 

У ThemeData есть textTheme и primaryTextTheme. Там можно настроить шрифты.

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +                      if (TextSearchFieldController.text.endsWith(' ') &&
есть такой метод `trim` - обрезает пробелы, лучше его использовать

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +                      if (TextSearchFieldController.text.endsWith(' ') &&
по хорошему вынести бы все проверки в отдельные методы

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +                decoration: InputDecoration(
по дизайну все поля оформлены в едином стиле и лучше все настройки сделать в теме

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +                        //клик на иконку фильтра
в поиске иконка фильтра не нужна
во время ввода текста кнопка очистить там находится

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +                          filteredSightsList = filteredListOfItems(
у вас поиск и фильтр это разные экраны и с собой не связаны
ну разве что во время поиска используются настройки фильтра

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/SightSearchScreen.dart
> +                          print(customList.map((e) => e.name));
debugPrint

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/res/themes.dart
> +  // ignore: prefer_const_constructors
👆

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/res/themes.dart
>  );
что-то маленькая у вас тема
хорошо бы добавить сюда настройки инпутов, у арбара можно тут тень отключить, настройки нижней навигации

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/sight_details.dart
> +  late Sight sight;
почему так?
надо сразу передавать в этот экран место, делайте финальное свойство

увидела s в конструкторе
зачем такие пути? можно сразу передать что надо

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/sight_details.dart
> +  late Sight sight;
да, и s очень информативное название свойства

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/sight_details.dart
>                            fontFamily: 'Roboto',
тема у нас зачем?

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/sight_details.dart
>                                  MaterialStateProperty.all<Color>(Colors.green),
зеленый цвет отличается оттенками в темной и светлой теме, поэтому цвета определяем в теме

если не хватает цветов, то можно использовать 
Экстеншены для темы, флаттер 3.0. Пример реализации:
https://medium.com/geekculture/flutter-3-how-to-extend-themedata-56b8923bf1aa

2023-01-23 20:36 UTC, internetova commented on lib/ui/screen/sight_list_screen.dart
> +import 'SightSearchScreen.dart';
https://dart.dev/guides/language/effective-dart/style

2023-02-11 10:43 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/218253908-4c50491b-5e7f-4070-8213-7583ade2f446.png)

2023-02-12 09:41 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/218303635-e43571d0-cee6-4edf-9259-755a84aa3e35.png)

2023-02-20 18:56 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/220181616-73231708-8229-4ed7-abb7-d4ec848be27d.png)
toast когда нет результата в поиске

2023-02-27 21:46 UTC, dutsky requested changes
В ресурсах и svg и png версии изображений. Желательно оставить только svg.

Обратите внимание на вёрстку. Желательно исправить
<img width="696" alt="image" src="https://user-images.githubusercontent.com/5102635/221692111-24586468-31fa-4e5b-a232-c2019508982d.png">

Желательно использовать тему.

Кажется нет экрана пустого состояния поиска 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/5102635/221692467-834f49ab-a88f-43f2-81c2-ecbe4eba3536.png">

Обращайте вниимание на ошибки анализатора.

Желательно не делать вёрстку в методах, лучше в виджетах.

Поиск лучше подправить -- сделать регистронезависимым и запоминать историю, даже если строка не найдена. Искать по мере поиска, а не только при нажатии на пробел

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +// ignore_for_file: non_constant_identifier_names
_minor_ желательно убрать

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +import 'package:flutter/widgets.dart';
_minor_ неиспользуемые импорты желательно убрать

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +
_minor_ у вас сам контроллер не будет изменяться, только поле `text`. Поэтому можно сделать его final

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +
_minor_ поля focus... можно инициализировать тут, кажется. И тогда `late` можно будет убрать

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +  Widget _suffixClearButton(
_minor_ если в этом нет прямой необходмости, то виджеты лучше не заменять методами:
https://www.youtube.com/watch?v=IOyq-eTRhvo
https://stackoverflow.com/questions/53234825/what-is-the-difference-between-functions-and-classes-to-create-reusable-widgets

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +    return SizedBox.shrink();
_minor_ в ide есть команда добавить const ко всем классам в файле, которые имеют константный конструктор. Лучше не пренебрегать этим правилом.

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +                          Navigator.pop(context);
кажется что после добавления нового места не обновляется экран

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/add_sight_screen.dart
> +                              'hotel',
здесь, кажется, можно указать реальную категорию.

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/categories_screen.dart
> +  String catChoised = AppStrings.noChoise;
_minor_ чуть выше анализатор уже ругается что в виджете объявлено не `final` поле

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/categories_screen.dart
> +  ChooseCategories({
_minor_ желательно чтоб файл и самый верхний класс в файле назывались одинаково

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/categories_screen.dart
> +      return const Text('');
```suggestion
      return const SizedBox.shrink();
```

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/categories_screen.dart
> +void clearChoise(choiseClear) {
_minor_ желательно указывать тип передаваемого значения

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/filters_screen.dart
>            Container(
контейнер -- достаточно навороченный виджет, если можно обойтись без него, то желательно это делать

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/sight_search_screen.dart
> +  late List<Sight> sightList;
в виджете не желательно держать не-final поля, да и анализатор об этом говорит

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/sight_search_screen.dart
> +          }
в дизайне есть пример экрана, для случая, когда ничего не найдено.

2023-02-27 21:46 UTC, dutsky commented on lib/ui/screen/sight_search_screen.dart
> +      if (checkSight.name.contains(inputMask)) {
желательно чтоб поиск был независим от регистра

2023-03-01 17:56 UTC, bigbagabum commented
Ок тогда возвращаю часть пробно переделанных иконок по просьбе предыдущего ревью из png в svg. Т.к. это не очень то правильно просить такие переделки с таким количеством приготовленых экранов ввиду отсутствия требования работать с svg в заданиях и уроках.

2023-04-05 20:39 UTC, bigbagabum commented on lib/ui/screen/categories_screen.dart
> +void clearChoise(choiseClear) {
так это функция которая ничего не возвращает а просто обнуляет

2023-04-05 20:40 UTC, bigbagabum commented on lib/ui/screen/add_sight_screen.dart
> +  Widget _suffixClearButton(
эти метода используются в дереве виджетов для кастомизации дерева от переменных, там ожидается виджет. Или лучше прям в дереве эту логику прописать? в чем разница?

2023-04-05 20:48 UTC, bigbagabum commented on lib/ui/screen/add_sight_screen.dart
> +import 'package:flutter/widgets.dart';
при удалении возникает ошибка не могу убрать

2023-04-05 20:50 UTC, bigbagabum commented on lib/ui/screen/add_sight_screen.dart
> +// ignore_for_file: non_constant_identifier_names
к комментарию выше. Поиск в ТЗ указан "искать после слова или по вводу. Другой проверяющий сказал делать по ТЗ, оставлю так"

2023-04-18 07:23 UTC, bigbagabum commented
![image](https://user-images.githubusercontent.com/78903783/232702391-f6c2af4f-335c-4e0d-a369-45289ec55aff.png)

2023-04-19 15:03 UTC, egrischenkov approved these changes

2023-04-22 03:49 UTC, merged